### ISSUE TITLE
error: ReferenceError: pathname is not defined

### ISSUE THREAD

**Issue by s9203** [dennisbaskin/electron-view-renderer#7]
Not working on my Windows 10.

**main.js**
```Javascript
const {app, BrowserWindow} = require('electron');
const path = require('path');
const url = require('url');
const ElectronViewRenderer = require('electron-view-renderer');
const viewRenderer = new ElectronViewRenderer({
    viewPath: 'views',
    viewProtocol: 'view'
});
viewRenderer.use('ejs');
let win;
function createWindow() {
    win = new BrowserWindow({
        width: 800,
        minWidth: 800,
    });
    viewRenderer.load(win, 'index', {name: 'Ghost'});
    win.on('closed', () => {
        win = null;
    });
}
```
**Console**
```console
error: ReferenceError: pathname is not defined
    at parseFilePath (C:\Users\app\WebstormProjects\app\node_modules\electron-view-renderer\index.js:14:48)
    at Promise (C:\Users\app\WebstormProjects\app\node_modules\electron-view-renderer\index.js:120:24)
    at ElectronViewRenderer.renderTemplate (C:\Users\app\WebstormProjects\app\node_modules\electron-view-renderer\index.js:117:12)
    at Function.protocol.registerBufferProtocol (C:\Users\app\WebstormProjects\app\node_modules\electron-view-renderer\index.js:136:12)
```

The directory views was created in the project folder.
Also created an index.ejs file

Absolute path to project:
`
C:\Users\app\WebstormProjects\app\*(main.js,views/,etc...)
`

**Comment by dennisbaskin** [comment]
Looks like I made a mistake on a variable name. This was only affecting windows platform. This is fixed in v1.2.3 in commit 9f1414367bf49b1d11669b6328c22055fc08aab3. Run `npm update electron-view-renderer` to get latest 😃 .
