### ISSUE TITLE
App threw an error when running TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by KamilKalfas** [dennisbaskin/electron-view-renderer#9]
Hi there,

I'm getting this error with your example code. 

Code sample:
```
const ElectronViewRenderer = require('electron-view-renderer')
let win
const viewRenderer = new ElectronViewRenderer({
  viewPath: 'views',
  viewProtcolName: 'view',
  useAssets: false,
  assetsPath: 'assets',
  assetsProtocolName: 'asset',
});
viewRenderer.use('ejs')

function createWindow() {
  win = new BrowserWindow({ width: 800, height: 600 })
  viewRenderer.load(win, 'index', { name: "Bob" })
}
```
Error:
```App threw an error when running TypeError: Cannot read property 'on' of undefined
    at ElectronViewRenderer.use (/Users/kka06/space/lit-config/node_modules/electron-view-renderer/index.js:155:8)
    at Object.<anonymous> (/Users/kka06/space/lit-config/index.js:14:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at loadApplicationPackage (/usr/local/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/default_app.asar/main.js:252:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/default_app.asar/main.js:292:5)
    at Module._compile (module.js:541:32)```

**Comment by dennisbaskin** [comment]
Hi @KamilKalfas,

Could you show me the full code you are testing with (the full example file). Also could you list your npm and node versions?

**Comment by dennisbaskin** [comment]
And also electron version too please

**Comment by dennisbaskin** [comment]
The following is the use method definition:

```
  use(name) {
    this._currentRenderer = this.renderers[name]

    app.on('ready', () => {
      this.setupViewProtocol()
      if (this.useAssets) this.setupAssetsProtocol()
    })
  }
```

The error is telling us that app is null

App is referenced (along with protocol) at the top of the module as follows: 

```
const {app, protocol} = require('electron')
```

So this leads me to ask: what is your your file structure and how are you starting the app?

**Comment by dennisbaskin** [comment]
One final note:

I see `electron-prebuilt`. I suggest trying with `electron` package instead. 

https://stackoverflow.com/questions/41574586/what-is-the-difference-between-electron-and-electron-prebuilt

**Comment by dennisbaskin** [comment]
see commit: d3faefb35d1f34e2e13401a399e45d2b70c314ea

**Comment by KamilKalfas** [comment]
@dennisbaskin yup my fault sorry mate, just figured out same as you, thanks anyway

**Comment by dennisbaskin** [comment]
No problem at all. Glad to help look where I can.
